language: ruby
script: bundle exec rake test
sudo: false
cache:
  - bundler
rvm:
  - 2.1
matrix:
  fast_finish: true
  include:
    - rvm: 1.9
      gemfile: gemfiles/chef-11/Gemfile
      script: bundle exec rspec spec
